## h2 DB TEST Config
spring:
  datasource:
   hikari:
     schema: classpath:sql/mysql_schema.sql
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/withPlace?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
   username: root
   password:

  sql:
    init:
      mode: always
      platform: mysql
      #data-locations: classpath*:db/data.sql
      schema-locations: classpath*:sql/mysql_schema.sql