
spring:
  profiles:
    active: h2
    #active: mssql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: false
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

server:
  port: 8081
